steps:
  - name: node:12
    args: ['npm', 'ci']

  - name: node:12
    args: ['npm', 'run', 'test']

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: [
      '-c',
      'bash <(curl -s https://codecov.io/bash) -t $(gcloud secrets versions access latest --secret codecov-token) -f coverage/lcov.info -F unittests -B $BRANCH_NAME -C -$COMMIT_SHA -b $BUILD_ID'
    ]
